FROM php:8.1-apache-buster

RUN apt-get update && apt-get install -y \
    git \
    libzip-dev \
    && docker-php-ext-install pdo_mysql zip \
    && docker-php-ext-install mysqli \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Copiar los archivos de la aplicación en el directorio de documentos de Apache
COPY ./ui /var/www/html/

EXPOSE 80

CMD ["apache2-foreground"]
