# Establece la imagen base
FROM node:14

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos package.json y package-lock.json
COPY AngularUI/package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Instala Angular CLI globalmente
RUN npm install -g @angular/cli

# Copia el resto de los archivos del proyecto
COPY AngularUI/. .

# Expone el puerto 4500
EXPOSE 4500

# Inicia el servidor de desarrollo de Angular
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4500"]